/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignalTickerRouteImport } from './routes/signal.$ticker'
import { Route as ApiPublicCronCheckSignalsRouteImport } from './routes/api.public.cron.check-signals'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalTickerRoute = SignalTickerRouteImport.update({
  id: '/signal/$ticker',
  path: '/signal/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronCheckSignalsRoute =
  ApiPublicCronCheckSignalsRouteImport.update({
    id: '/api/public/cron/check-signals',
    path: '/api/public/cron/check-signals',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/signal/$ticker': typeof SignalTickerRoute
  '/api/public/cron/check-signals': typeof ApiPublicCronCheckSignalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/signal/$ticker': typeof SignalTickerRoute
  '/api/public/cron/check-signals': typeof ApiPublicCronCheckSignalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/signal/$ticker': typeof SignalTickerRoute
  '/api/public/cron/check-signals': typeof ApiPublicCronCheckSignalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/signal/$ticker'
    | '/api/public/cron/check-signals'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/signal/$ticker' | '/api/public/cron/check-signals'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/signal/$ticker'
    | '/api/public/cron/check-signals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  SignalTickerRoute: typeof SignalTickerRoute
  ApiPublicCronCheckSignalsRoute: typeof ApiPublicCronCheckSignalsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signal/$ticker': {
      id: '/signal/$ticker'
      path: '/signal/$ticker'
      fullPath: '/signal/$ticker'
      preLoaderRoute: typeof SignalTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/check-signals': {
      id: '/api/public/cron/check-signals'
      path: '/api/public/cron/check-signals'
      fullPath: '/api/public/cron/check-signals'
      preLoaderRoute: typeof ApiPublicCronCheckSignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  SignalTickerRoute: SignalTickerRoute,
  ApiPublicCronCheckSignalsRoute: ApiPublicCronCheckSignalsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
